### ISSUE TITLE
run helloworld as a test will panic

### ISSUE THREAD

**Issue by axiaoxin** [rivo/tview#591]
define the helloworld demo as a function:
```
func Run() {
	box := tview.NewBox().SetBorder(true).SetTitle("Hello, world!")
	if err := tview.NewApplication().SetRoot(box, true).Run(); err != nil {
		panic(err)
	}
}
```

write a testing:
```

func TestRun(t *testing.T) {
	Run()
}
```

run test:
```
go test -run TestRun
--- FAIL: TestRun (0.00s)
panic: operation not supported by device [recovered]
	panic: operation not supported by device

goroutine 18 [running]:
testing.tRunner.func1.2(0x118e680, 0x12b4218)
	/usr/local/Cellar/go/1.16/libexec/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000082600)
	/usr/local/Cellar/go/1.16/libexec/src/testing/testing.go:1147 +0x4b6
panic(0x118e680, 0x12b4218)
	/usr/local/Cellar/go/1.16/libexec/src/runtime/panic.go:965 +0x1b9
github.com/axiaoxin-com/x-stock/ui/terminal.Run()
	/Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/ui/terminal/terminal.go:11 +0x20c
github.com/axiaoxin-com/x-stock/ui/terminal.TestRun(0xc000082600)
	/Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/ui/terminal/terminal_test.go:6 +0x25
testing.tRunner(0xc000082600, 0x11bf890)
	/usr/local/Cellar/go/1.16/libexec/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.16/libexec/src/testing/testing.go:1239 +0x2b3
exit status 2
```

**Comment by rivo** [comment]
Your call stack doesn't list any `tview` code and this panic is not generated by it. I'm pretty sure what you're trying to do won't work anyway. Running a `tview` application captures the entire screen and it's interactive. It won't even exit unless you hit Ctrl-C. But unit tests are supposed to run unsupervised so this is at the very least not a good fit.

If you insist on trying to get this to work, please try it with a small `tcell` application first. If that works, it's likely we can make it work with `tview` as well.
