### ISSUE TITLE
panic when scrolling textview

### ISSUE THREAD

**Issue by SamWhited** [rivo/tview#636]
When calling `ScrollTo` on a textview I'm frequently getting the following (trimmed to relevant parts) panic starting in the textview's draw function at line 1017:

```
$ go run .
panic: runtime error: index out of range [100] with length 0 [recovered]
        panic: runtime error: index out of range [100] with length 0

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        /home/sam/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/application.go:243 +0x4d
panic({0x946f80, 0xc00059b200})
        /home/sam/gotip/src/runtime/panic.go:1038 +0x215
github.com/rivo/tview.(*TextView).Draw(0xc0000bc100, {0xa43700, 0xc000568000})
        /home/sam/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/textview.go:1017 +0xdf4
```

**Comment by rivo** [comment]
Please see https://github.com/rivo/tview/wiki/Concurrency. Most of the functions are not thread-safe. You need to take care of that yourself. (The `Write()` function is an exception and I'm not sure if, for consistency reasons, it should've been like the other functions.)

**Comment by SamWhited** [comment]
This is all happening synchronously and there should be no race possible here

**Comment by rivo** [comment]
I don't see your code so it's hard to say. Do you write to the `TextView` using the `io.Writer` interface, calling `Clear()` periodically? And other parts of the program could cause a non-main-thread redraw. Is this a correct assumption?

**Comment by SamWhited** [comment]
I think so, I haven't managed to get this into an easily reproducible form, and it's been long enough that I don't really remember what was happening now. It is possible (though unlikely, I think?) that other areas of the code could be calling `app.Redraw()` which could be trickling down to this.

**Comment by SamWhited** [comment]
I have tested this, I still get the panic even with locking around the scrolling.

**Comment by rivo** [comment]
Responding to https://github.com/rivo/tview/pull/641#issuecomment-925438772 here: This is actually what I would like to suggest. In fact, if it weren't for backwards compatibility, I'd probably even remove the lock from the `Write()` function and leave everything up to the user.

When I implemented this, I was under the impression that implementing the `io.Writer` interface required thread safety so I introduced a mutex. Now it's a bit inconsistent, leading to the confusion outlined in this issue. That's my bad.

But removing the lock completely might break existing implementations. I'm very reluctant to do this.

**Comment by SamWhited** [comment]
As much as it clutters the API, I wonder if for backwards compatibility purposes we could use two constructors for this? eg. the existing `NewTextView` would continue to work as sis, but `NewTextViewUnsafe` or something would create one with an internal property set that skips over the locking?
